import WilAjaxSelectTwo from "./../components/dumbs/WilAjaxSelectTwo.vue";
import WilCheckbox from "./../components/dumbs/WilCheckbox.vue";
import WilInput from "./../components/dumbs/WilInput.vue";
import WilSwitch from "./../components/dumbs/WilSwitch.vue";
import WilTextarea from "./../components/dumbs/WilTextarea.vue";
import WilImgCheckbox from "./../components/dumbs/WilImgCheckbox.vue";
import WilRadio from "./../components/dumbs/WilRadio.vue";
import WilSelectTwo from "./../components/dumbs/WilSelectTwo.vue";
import WilSelectTree from "./../components/dumbs/WilSelectTree.vue";
import WilButton from "./../components/dumbs/buttons/WilButton.vue";
import WilLink from "./../components/dumbs/buttons/WilLink.vue";
import WilPagination from "./../components/dumbs/WilPagination.vue";
import WilBlockLoading from "./../components/dumbs/loading/WilBlockLoading.vue";
import WilLineLoading from "./../components/dumbs/loading/WilLineLoading.vue";
import WilWaveLoading from "./../components/dumbs/WilWaveLoading.vue";
import WilAlert from "./../components/dumbs/WilAlert.vue";
import WilAlertAnimation from "./../components/dumbs/WilAlertAnimation.vue";
import WilToggleBtn from "./../components/dumbs/WilToggleBtn.vue";
import WilFieldErrorMsg from "./../components/dumbs/WilFieldErrorMsg.vue";
import WilGridItem from "./../components/smart/Grid/WilGridItem.vue";
import WilEventItem from "./../components/smart/Grid/WilEventItem.vue";
import WilPopup from "./../components/smart/Popup/WilPopup.vue";
import WilConfirmationPopup from "./../components/dumbs/popup/WilConfirmationPopup.vue";
import WilGrid from "./../components/smart/Grid/WilGrid.vue";
import WilLazyLoadComponent from "./../components/smart/LazyLoadComponent/WilLazyLoadComponent.vue";
import WilSimpleSelect from "./../components/dumbs/WilSimpleSelect.vue";
import WilHeading from "./../components/dumbs/WilHeading.vue";
import WilHeadingTitle from "./../components/dumbs/WilHeadingTitle.vue";
import WilLists from "./../components/smart/ListItems/WilLists.vue";
import WilListItem from "./../components/dumbs/list-item/WilListItem.vue";
import WilTable from "./../components/smart/Table/WilTable.vue";
import WilTHead from "./../components/smart/Table/WilTHead.vue";
import WilGallery from "./../components/smart/Gallery/WilGallery.vue";
import WilGalleryBtn from "./../components/smart/Gallery/WilGalleryBtn.vue";
import WilSecondGallery from "./../components/smart/Gallery/WilSecondGallery.vue";
import WilRestaurantMenuItems from "./../components/smart/Restaurant/WilRestaurantMenuItems.vue";
import WilClaimBtn from "./../components/smart/Claim/WilClaimBtn.vue";
import WilButtonsDropdown from "./../components/dumbs/buttons/WilButtonsDropdown.vue";
import WilToggleController from "./../components/dumbs/WilToggleController.vue";
import WilSectionHeading from "./../components/smart/Section/WilSectionHeading.vue";
import WilSocialSharingBtn from "./../components/smart/SocialSharing/WilSocialSharingBtn.vue";
import Facebook from "./../components/smart/LoginRegister/Facebook.vue";
export default {
  install(Vue) {
    Vue.component(WilToggleController.name, WilToggleController);
    Vue.component(WilSocialSharingBtn.name, WilSocialSharingBtn);
    Vue.component(WilButtonsDropdown.name, WilButtonsDropdown);
    Vue.component(WilAjaxSelectTwo.name, WilAjaxSelectTwo);
    Vue.component(WilCheckbox.name, WilCheckbox);
    Vue.component(WilSwitch.name, WilSwitch);
    Vue.component(WilInput.name, WilInput);
    Vue.component(WilRadio.name, WilRadio);
    Vue.component(WilSimpleSelect.name, WilSimpleSelect);
    Vue.component(WilSelectTwo.name, WilSelectTwo);
    Vue.component(WilButton.name, WilButton);
    Vue.component(WilLink.name, WilLink);
    Vue.component(WilGrid.name, WilGrid);
    Vue.component(WilGridItem.name, WilGridItem);
    Vue.component(WilEventItem.name, WilEventItem);
    Vue.component(WilLineLoading.name, WilLineLoading);
    Vue.component(WilBlockLoading.name, WilBlockLoading);
    Vue.component(WilWaveLoading.name, WilWaveLoading);
    Vue.component(WilAlert.name, WilAlert);
    Vue.component(WilAlertAnimation.name, WilAlertAnimation);
    Vue.component(WilToggleBtn.name, WilToggleBtn);
    Vue.component(WilPopup.name, WilPopup);
    Vue.component(WilConfirmationPopup.name, WilConfirmationPopup);
    Vue.component(WilSelectTree.name, WilSelectTree);
    Vue.component(WilTextarea.name, WilTextarea);
    Vue.component(WilFieldErrorMsg.name, WilFieldErrorMsg);
    Vue.component(WilLazyLoadComponent.name, WilLazyLoadComponent);
    Vue.component(WilHeading.name, WilHeading);
    Vue.component(WilHeadingTitle.name, WilHeadingTitle);
    Vue.component(WilLists.name, WilLists);
    Vue.component(WilListItem.name, WilListItem);
    Vue.component(WilTable.name, WilTable);
    Vue.component(WilTHead.name, WilTHead);
    Vue.component(WilImgCheckbox.name, WilImgCheckbox);
    Vue.component(WilPagination.name, WilPagination);
    Vue.component(WilGalleryBtn.name, WilGalleryBtn);
    Vue.component(WilGallery.name, WilGallery);
    Vue.component(WilSecondGallery.name, WilSecondGallery);
    Vue.component(WilRestaurantMenuItems.name, WilRestaurantMenuItems);
    Vue.component(WilClaimBtn.name, WilClaimBtn);
    Vue.component(WilSectionHeading.name, WilSectionHeading);
    Vue.component(Facebook.name, Facebook);
  }
};
